name: fiscaliza
channels:
  - conda-forge
dependencies:
  - ca-certificates=2022.4.26
  - certifi=2021.10.8
  - openssl=1.1.1o
  - pip=21.2.4
  - python=3.9.0
  - setuptools=61.2.0
  - sqlite=3.38.3
  - tzdata=2022a
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.1
  - wincertstore=0.2
  - pip:
      - charset-normalizer==2.0.12
      - colorama==0.4.4
      - commonmark==0.9.1
      - fastcore==1.5.28
      - fiscaliza==0.2.20
      - idna==3.3
      - packaging==21.3
      - pygments==2.12.0
      - pyparsing==3.0.9
      - python-redmine==2.3.0
      - requests==2.27.1
      - rich==10.2.1
      - tabulate==0.9.0
      - unidecode==1.3.6
      - urllib3==1.26.9
