name: fiscaliza
channels:
  - conda-forge
  - defaults
dependencies:
  - bleach=3.3.1
  - brotlipy=0.7.0
  - ca-certificates=2021.5.30
  - certifi=2021.5.30
  - cffi=1.14.6
  - chardet=4.0.0
  - cmarkgfm=0.6.0
  - colorama=0.4.4
  - cryptography=3.4.7
  - docutils=0.17.1
  - importlib-metadata=4.6.1
  - importlib_metadata=4.6.1
  - keyring=23.0.1
  - openssl=1.1.1k
  - packaging=21.0
  - pip=21.1.3
  - pkginfo=1.7.1
  - pycparser=2.20
  - pygments=2.9.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - python=3.8.10
  - python_abi=3.8
  - pywin32-ctypes=0.2.0
  - readme_renderer=27.0
  - requests=2.26.0
  - requests-toolbelt=0.9.1
  - rfc3986=1.5.0
  - setuptools=49.6.0
  - six=1.16.0
  - sqlite=3.36.0
  - tqdm=4.61.2
  - twine=3.4.1
  - ucrt=10.0.20348.0
  - urllib3=1.26.6
  - vc=14.2
  - vs2015_runtime=14.29.30037
  - wheel=0.36.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - zipp=3.5.0
  - pip:
      - appdirs==1.4.4
      - argon2-cffi==20.1.0
      - asttokens==2.0.5
      - attrs==21.2.0
      - backcall==0.2.0
      - black==21.7b0
      - charset-normalizer==2.0.3
      - cheap-repr==0.4.6
      - click==8.0.1
      - commonmark==0.9.1
      - debugpy==1.3.0
      - decorator==5.0.9
      - defusedxml==0.7.1
      - entrypoints==0.3
      - executing==0.8.0
      - fastcore==1.3.20
      - fastrelease==0.1.11
      - ghapi==0.1.19
      - idna==3.2
      - ipykernel==6.0.3
      - ipython==7.25.0
      - ipython-genutils==0.2.0
      - ipywidgets==7.6.3
      - jedi==0.18.0
      - jinja2==3.0.1
      - jsonschema==3.2.0
      - jupyter==1.0.0
      - jupyter-client==6.1.12
      - jupyter-console==6.4.0
      - jupyter-core==4.7.1
      - jupyterlab-widgets==1.0.0
      - markupsafe==2.0.1
      - matplotlib-inline==0.1.2
      - mistune==0.8.4
      - mypy==0.910
      - mypy-extensions==0.4.3
      - nbconvert==5.6.1
      - nbdev==1.1.14
      - nbformat==5.1.3
      - notebook==6.4.0
      - pandocfilters==1.4.3
      - parso==0.8.2
      - pathspec==0.9.0
      - pickleshare==0.7.5
      - prometheus-client==0.11.0
      - prompt-toolkit==3.0.19
      - pyrsistent==0.18.0
      - python-dateutil==2.8.2
      - python-redmine==2.3.0
      - pywin32==301
      - pywinpty==1.1.3
      - pyyaml==5.4.1
      - pyzmq==22.1.0
      - qtconsole==5.1.1
      - qtpy==1.9.0
      - regex==2021.7.6
      - rich==10.6.0
      - send2trash==1.7.1
      - snoop==0.4.0
      - tabulate==0.8.9
      - terminado==0.10.1
      - testpath==0.5.0
      - toml==0.10.2
      - tomli==1.0.4
      - tornado==6.1
      - traitlets==5.0.5
      - typing-extensions==3.10.0.0
      - unidecode==1.2.0
      - wcwidth==0.2.5
      - webencodings==0.5.1
      - widgetsnbextension==3.5.1
