# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"URL": "constants.ipynb",
         "URLHM": "constants.ipynb",
         "URLHM2": "constants.ipynb",
         "ACAO_DESCRIPTION": "constants.ipynb",
         "ACAO_TRACKER": "constants.ipynb",
         "KWARGS": "constants.ipynb",
         "IDS": "constants.ipynb",
         "FIELDS": "constants.ipynb",
         "JSON_FIELDS": "constants.ipynb",
         "STATUS": "constants.ipynb",
         "FIELD2ID": "constants.ipynb",
         "TABLECOLS": "constants.ipynb",
         "SITUACAO": "constants.ipynb",
         "CANCELADA": "constants.ipynb",
         "RELATADA": "constants.ipynb",
         "CLASSE": "constants.ipynb",
         "TIPO": "constants.ipynb",
         "SERVICOS": "constants.ipynb",
         "PF": "constants.ipynb",
         "PROCEDIMENTOS": "constants.ipynb",
         "ESTADOS": "constants.ipynb",
         "MUNICIPIOS": "constants.ipynb",
         "journal2table": "format.ipynb",
         "value_text_string": "format.ipynb",
         "check_update": "format.ipynb",
         "view_string": "format.ipynb",
         "KEYS_TO_DISCARD": "info.ipynb",
         "insp2acao": "info.ipynb",
         "issue_type": "info.ipynb",
         "utf2ascii": "info.ipynb",
         "detalhar_issue": "info.ipynb",
         "download_attachments": "info.ipynb",
         "extract_attachment": "info.ipynb",
         "extract_attachments": "info.ipynb",
         "atualiza_fiscaliza": "update.ipynb",
         "del_attach": "update.ipynb",
         "excluir_relatorio": "update.ipynb",
         "gerar_relatorio": "update.ipynb",
         "relatar_inspecao": "update.ipynb",
         "date_pattern": "validation.ipynb",
         "issue2users": "validation.ipynb",
         "auth_user": "validation.ipynb",
         "valida_fiscaliza": "validation.ipynb",
         "parse_dict": "validation.ipynb",
         "validar_dados": "validation.ipynb",
         "DICT_FIELDS": "validation.ipynb"}

modules = ["constants.py",
           "format.py",
           "info.py",
           "update.py",
           "validation.py"]

doc_url = "https://ronaldokun.github.io/fiscaliza/"

git_url = "https://github.com/ronaldokun/fiscaliza/tree/master/"

def custom_doc_links(name): return None
